baseURL = "http://example.org/"
languageCode = "en-gb"
title = "AceCentral"
theme = "slate"

[ params ]
OpenLinksInNewWindow = true
Favicon = "favicon.ico"

# list of nav tags
[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "projects"
tag = "project"
icon = "briefcase"

[[ params.nav ]]
name = "forms"
tag = "form"
icon = "WPForms"

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "AAC Devices"
tag = "aac"
icon = "tablet"

[[ params.nav ]]
name = "Internet resources (bookmarks etc)"
tag = "resources"
icon = "book"

[[ params.nav ]]
name = "social media"
tag = "social-media"
icon = "facebook"
